// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rugoqenajhbjqcmrplac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1Z29xZW5hamhianFjbXJwbGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzAwMDIsImV4cCI6MjA3MzA0NjAwMn0.fI_kCctLb0HSaI1C8PYMQrok1qtK6DadqGhgIHj98Og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});